#!/usr/bin/env python3
"""Build the versioned single-file distribution from the standard Skill."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
REFERENCES = (
    "pedagogy-and-stages.md",
    "image-grammar.md",
    "generation-protocol.md",
    "writing-and-compliance.md",
)


def version() -> str:
    return (ROOT / "VERSION").read_text(encoding="utf-8").strip()


def render() -> str:
    sections = [
        "<!-- Generated by tools/build_portable.py. Do not edit directly. -->\n",
        (ROOT / "SKILL.md").read_text(encoding="utf-8").rstrip(),
    ]
    for filename in REFERENCES:
        source = ROOT / "references" / filename
        sections.extend(
            (
                f"\n\n---\n\n<!-- Embedded reference: references/{filename} -->\n",
                source.read_text(encoding="utf-8").rstrip(),
            )
        )
    return "".join(sections) + "\n"


def output_path() -> Path:
    return ROOT / "dist" / f"blackboard-design-skill-portable-v{version()}.md"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed Portable file differs from generated content",
    )
    args = parser.parse_args()
    expected = render()
    destination = output_path()

    if args.check:
        if not destination.is_file() or destination.read_text(encoding="utf-8") != expected:
            print(f"Portable file is stale: {destination.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"Portable file is current: {destination.relative_to(ROOT)}")
        return 0

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(expected, encoding="utf-8")
    print(f"Built {destination.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
