#!/usr/bin/env python3
"""Build the versioned single-file distribution from the standard Skill."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
REFERENCE_CONFIG = (
    ("pedagogy-and-stages.md", "学段与育人路由", "portable-reference-pedagogy-and-stages"),
    ("image-grammar.md", "板面与图像语法", "portable-reference-image-grammar"),
    ("generation-protocol.md", "生成与修改协议", "portable-reference-generation-protocol"),
    ("writing-and-compliance.md", "文案与合规", "portable-reference-writing-and-compliance"),
)


def version() -> str:
    return (ROOT / "VERSION").read_text(encoding="utf-8").strip()


def split_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---\n"):
        raise ValueError("SKILL.md must begin with YAML frontmatter")
    marker = "\n---\n"
    end = text.find(marker, 4)
    if end == -1:
        raise ValueError("SKILL.md frontmatter is not closed")
    frontmatter = text[: end + len(marker)]
    body = text[end + len(marker) :].lstrip("\n")
    return frontmatter, body


def strip_reference_title(text: str) -> str:
    lines = text.rstrip().splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
        while lines and not lines[0].strip():
            lines = lines[1:]
    return "\n".join(lines).rstrip()


def render() -> str:
    frontmatter, body = split_frontmatter((ROOT / "SKILL.md").read_text(encoding="utf-8"))

    for filename, label, anchor in REFERENCE_CONFIG:
        body = body.replace(
            f"[{label}](references/{filename})",
            f"[{label}](#{anchor})",
        )

    sections = [
        frontmatter.rstrip(),
        "\n\n<!-- Generated by tools/build_portable.py. Do not edit directly. -->\n",
        "\n> **Portable 单文件说明：** 本文件已在后文内嵌全部 `references/` 专业规则。"
        "遇到引用链接时，请跳转到本文件后方对应的‘内嵌参考’章节，"
        "不要尝试访问外部目录。\n\n",
        body.rstrip(),
    ]

    for filename, label, anchor in REFERENCE_CONFIG:
        source = ROOT / "references" / filename
        sections.extend(
            (
                f'\n\n---\n\n<a id="{anchor}"></a>\n\n## 内嵌参考：{label}\n\n',
                strip_reference_title(source.read_text(encoding="utf-8")),
            )
        )

    return "".join(sections).rstrip() + "\n"


def output_path() -> Path:
    return ROOT / "dist" / f"blackboard-design-skill-portable-v{version()}.md"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed Portable file differs from generated content",
    )
    args = parser.parse_args()
    expected = render()
    destination = output_path()

    if args.check:
        if not destination.is_file() or destination.read_text(encoding="utf-8") != expected:
            print(f"Portable file is stale: {destination.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"Portable file is current: {destination.relative_to(ROOT)}")
        return 0

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(expected, encoding="utf-8")
    print(f"Built {destination.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
